// src/routes/auth/adminlogin/index.svelte
<script lang="ts">
	import { session } from '$app/stores';
	import { send } from '../../../lib/api';

	export let error: string;

	async function login(event: SubmitEvent) {
		const formEl = event.target as HTMLFormElement;
		const response = await send(formEl);

		if (response.error) {
			error = response.error;
		}

		$session.user = response.user;

		formEl.reset();
	}
</script>

<main class="main">
	<div class="login-form">
		<!-- Logo -->
		<div class="logo">
			<img
				src="https://raw.githubusercontent.com/Instar-Group/instar-web/41958dc9fdee1fca654f8ff9e0c9732d325ad5af/static/InstarLogo.svg"
				alt="logo"
				height="100"
				width="100"
			/>
			<span class="logo-text">Instar</span>
		</div>
		<!-- Login Form  -->
		<form
			class="bg-white shadow-md rounded content-center flex flex-col px-8 pt-6 pb-8 mb-4"
			on:submit|preventDefault={login}
			method="post"
		>
			<span class="text-2xl flex items-center justify-center text-center mb-4">Admin Login</span>
			<div class="mb-4">
				<label class="block text-gray-700 text-sm font-bold mb-2" for="username">Username</label>
				<input
					class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
					id="username"
					name="username"
					required
					type="text"
				/>
			</div>
			<div class="mb-6">
				<label class="block text-gray-700 text-sm font-bold mb-2" for="password">Password</label>
				<input
					class="shadow appearance-none border  rounded w-full py-2 px-3 text-gray-700 mb-3 leading-tight focus:outline-none focus:shadow-outline"
					id="password"
					name="password"
					required
					type="password"
				/>
			</div>

			{#if error}
				<p class="error">{error}</p>
			{/if}

			<button
				class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline"
				type="submit">submit</button
			>
		</form>
	</div>
</main>

<style>
	.main {
		@apply flex items-center justify-center;
	}
	.login-form {
		@apply w-full max-w-xs space-y-10 flex flex-col items-center justify-center;
	}
	.logo {
		@apply flex flex-row 
		scale-[.6]
		md:scale-100
		lg:scale-100;
	}
	.logo-text {
		@apply text-white  text-4xl items-center justify-center flex
		mx-3;
	}
	.error{
		@apply text-red-600 pb-4 text-center
	}
</style>

// instar/pages/auth/adminlogin.tsx
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import {  signIn } from "next-auth/react";

const adminlogin: NextPage = () => {
  const handleSignIn = (e:any) => {
    e.preventDefault();
    const username:any = e.target.username.value;
    const password:any = e.target.password.value;
    signIn("credentials", {
      username: username,
      password: password,
      callbackUrl: "/admin/adminconsole",
    });
  };
  return (
    <div>
      <Head>
        <title>Login</title>
        <link rel="icon" href="/favicon.svg" />
      </Head>

      <main className=" flex flex-col relative items-center space-y-10 justify-center">
        {/* Logo */}
        <div className="logo">
          <Image
            src="/images/InstarLogo.svg"
            alt="Logo"
            width={70}
            height={70}
          />
          <span className="logo-text">Instar</span>
        </div>

        {/* Login Form */}
        <form
          className="bg-slate-500 flex flex-col items-center  p-7 rounded-3xl space-y-6 shadow-2xl"
          onSubmit={handleSignIn}
        >
          <span className="text-white text-3xl">Admin Login</span>
          {/* Username input */}
          <div>
            <label className="block text-slate-200 text-base font-bold mb-2">
              Username
            </label>
            <input
              className="shadow appearance-none border rounded w-full py-2 px-3 text-slate-600 leading-tight focus:outline-none focus:shadow-outline"
              name="username"
              id="username"
              type="text"
            />
          </div>
          {/* Password input */}
          <div>
            <label className="block text-slate-200 text-base font-bold mb-2">
              Password
            </label>
            <input
              className="shadow appearance-none border rounded w-full py-2 px-3 text-slate-600 leading-tight focus:outline-none focus:shadow-outline"
              id="password"
              name="password"
              type="password"
            />
          </div>
          <div>
            <button
              type="submit"
              className="text-white bg-blue-600 hover:bg-blue-500 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-2 mb-2"
            >
              Login
            </button>
          </div>
        </form>
      </main>
    </div>
  );
};



export default adminlogin;
